services:
  app:
    build: .
    ports:
      - "2310:2310"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
    - ./module/ndms:/service/module/ndms
    command: ls
